sudo: required
services:
   - docker

before_install:
  - docker build -t rmnresende/travis-ci-test -f Dockerfile.dev .

script:
  - docker run -e CI=true rmnresende/travis-ci-test npm run test

language: generic